### PR TITLE
MNT: rerender

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #2.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

### CODE REVIEW

**Comment by PertuyF** [comment]
@conda-forge/r-deriv Please bump build number, then we should be ready to merge.

**Comment by PertuyF** [comment]
@jdblischak could you have a look?

**Comment by cbrueffer** [comment]
@PertuyF please bump the build number, then it's ready for merge

Edit: oops, I see. I'll bump it

**Comment by cbrueffer** [comment]
https://github.com/conda-forge/r-deriv-feedstock/pull/4 merged.

**Comment by PertuyF** [comment]
Thanks @cbrueffer !

**Pull request closed without merging**
